Repository Freshly/flow, pull requests merged in 2019-05, with the labels that each got.

#83 Remove Rewind
  README.md
  docs/images/revert.png
  lib/flow/concerns/transaction_wrapper.rb
  lib/flow/custom_matchers/wrap_in_transaction.rb
  lib/flow/flow/callbacks.rb
  lib/flow/flow/ebb.rb
  lib/flow/flow/flux.rb
  lib/flow/flow/revert.rb
  lib/flow/flow/status.rb
  lib/flow/flow/transactions.rb
  lib/flow/flow_base.rb
  lib/flow/operation/callbacks.rb
  lib/flow/operation/rewind.rb
  lib/flow/operation/status.rb
  lib/flow/operation/transactions.rb
  lib/flow/operation_base.rb
  lib/generators/rspec/application_operation/templates/application_operation_spec.rb
  lib/generators/rspec/flow/templates/flow_spec.rb.erb
  spec/flow/callbacks_spec.rb
  spec/flow/ebb_spec.rb
  spec/flow/flow_base_spec.rb
  spec/flow/flux_spec.rb
  spec/flow/operation/callbacks_spec.rb
  spec/flow/operation/rewind_spec.rb
  spec/flow/operation/status_spec.rb
  spec/flow/operation/transactions_spec.rb
  spec/flow/operation_base_spec.rb
  spec/flow/revert_spec.rb
  spec/flow/status_spec.rb
  spec/flow/transactions_spec.rb
  spec/integration/bottles_on_the_wall_flow_spec.rb
  spec/integration/flow_integration_spec.rb
  spec/integration/pass_bottles_around_spec.rb
  spec/integration/take_bottles_down_spec.rb
  spec/spec_helper.rb
  spec/support/shared_examples/a_transaction_wrapper.rb
  spec/support/shared_examples/method_is_wrapped_in_a_transaction.rb
  spec/support/shared_examples/methods_are_wrapped_in_a_transaction.rb
  spec/support/shared_examples/methods_are_wrapped_in_a_transaction_with_a_variety_of_input.rb
  spec/support/test_classes/bottles_on_the_wall_flow.rb
  spec/support/test_classes/pass_bottles_around.rb
  spec/support/test_classes/take_bottles_down.rb
Labels: Correction

#85 Operation.handle_errors Method
  lib/flow/operation/error_handler.rb
  spec/flow/operation/error_handler_spec.rb
  spec/support/test_classes/pass_bottles_around.rb
Labels: Feature

#63 state accessors!
  Gemfile.lock
  flow.gemspec
  lib/flow/operation/accessors.rb
  lib/flow/operation_base.rb
  spec/flow/operation/accessors_spec.rb
  spec/flow/operation_base_spec.rb
Labels: Feature

#90 Prevent Nil
  README.md
  lib/flow/custom_matchers/define_argument.rb
  lib/flow/state/arguments.rb
  lib/generators/flow/state/templates/state.rb.erb
  lib/generators/rspec/state/templates/state_spec.rb.erb
  spec/flow/state/arguments_spec.rb
  spec/integration/bottles_on_the_wall_state_spec.rb
  spec/support/test_classes/bottles_on_the_wall_state.rb
Labels: Feature

#94 switch changelog to markdown, add unreleased changes
  CHANGELOG.md
  CHANGELOG.txt
Labels: Correction

#95 dup inherited state accessor trackers
  Gemfile.lock
  flow.gemspec
  lib/flow/operation/accessors.rb
  spec/flow/operation/accessors_spec.rb
Labels: Correction

#96 Gem Updates
  .codeclimate.yml
  Gemfile.lock
  flow.gemspec
Labels: Correction, Maintenance

#98 Prevent Double Run Bug
  lib/flow/state/output.rb
  spec/flow/state/output_spec.rb
Labels: Correction

#99 Update Spicerack
  Gemfile.lock
  flow.gemspec
  spec/flow/trigger_spec.rb
Labels: Precursor

#100 Use Instructor::Base
  lib/flow.rb
  lib/flow/state/arguments.rb
  lib/flow/state/attributes.rb
  lib/flow/state/callbacks.rb
  lib/flow/state/core.rb
  lib/flow/state/defaults.rb
  lib/flow/state/options.rb
  lib/flow/state/string.rb
  lib/flow/state_base.rb
  spec/flow/state/arguments_spec.rb
  spec/flow/state/attributes_spec.rb
  spec/flow/state/callbacks_spec.rb
  spec/flow/state/core_spec.rb
  spec/flow/state/defaults/value_spec.rb
  spec/flow/state/defaults_spec.rb
  spec/flow/state/options_spec.rb
  spec/flow/state/output_spec.rb
  spec/flow/state/status_spec.rb
  spec/flow/state/string_spec.rb
  spec/flow/state_base_spec.rb
  spec/spec_helper.rb
  spec/support/shared_context/with_an_example_state.rb
  spec/support/shared_examples/a_class_with_attributes_having_default_values.rb
Labels: Refactoring

#101 Bump Spicerack
  Gemfile.lock
  flow.gemspec
Labels: Precursor

#102 Instructor Spec Cleanup
  lib/flow/custom_matchers.rb
  lib/flow/custom_matchers/define_argument.rb
  lib/flow/custom_matchers/define_attribute.rb
  lib/flow/custom_matchers/define_option.rb
  lib/flow/spec_helper.rb
  spec/flow/state/output_spec.rb
  spec/spec_helper.rb
  spec/support/shared_examples/a_class_which_defines_into_a_class_collection.rb
Labels: Refactoring

#103 Release 0.10.0
  CHANGELOG.md
  Gemfile.lock
  flow.gemspec
  lib/flow/version.rb
Labels: Release

#104 Release 0.10.0
  .codeclimate.yml
  CHANGELOG.md
  CHANGELOG.txt
  Gemfile.lock
  README.md
  flow.gemspec
  lib/flow.rb
  lib/flow/custom_matchers.rb
  lib/flow/custom_matchers/define_argument.rb
  lib/flow/custom_matchers/define_attribute.rb
  lib/flow/custom_matchers/define_option.rb
  lib/flow/custom_matchers/have_on_state.rb
  lib/flow/operation/accessors.rb
  lib/flow/rspec_configuration.rb
  lib/flow/spec_helper.rb
  lib/flow/state/arguments.rb
  lib/flow/state/attributes.rb
  lib/flow/state/callbacks.rb
  lib/flow/state/core.rb
  lib/flow/state/defaults.rb
  lib/flow/state/options.rb
  lib/flow/state/output.rb
  lib/flow/state/string.rb
  lib/flow/state_base.rb
  lib/flow/version.rb
  spec/flow/operation/accessors_spec.rb
  spec/flow/state/arguments_spec.rb
  spec/flow/state/attributes_spec.rb
  spec/flow/state/callbacks_spec.rb
  spec/flow/state/core_spec.rb
  spec/flow/state/defaults/value_spec.rb
  spec/flow/state/defaults_spec.rb
  spec/flow/state/options_spec.rb
  spec/flow/state/output_spec.rb
  spec/flow/state/status_spec.rb
  spec/flow/state/string_spec.rb
  spec/flow/state_base_spec.rb
  spec/flow/trigger_spec.rb
  spec/spec_helper.rb
  spec/support/shared_context/with_an_example_state.rb
  spec/support/shared_examples/a_class_which_defines_into_a_class_collection.rb
  spec/support/shared_examples/a_class_with_attributes_having_default_values.rb
Labels: Release

#105 bump spicerack
  Gemfile.lock
  flow.gemspec
Labels: Maintenance

#107 Spicerack 0.13.0
  Gemfile.lock
  flow.gemspec
  lib/flow.rb
  lib/flow/spec_helper.rb
  lib/flow/state_base.rb
  spec/flow/state/output_spec.rb
  spec/flow/state_base_spec.rb
  spec/support/shared_context/with_an_example_state.rb
Labels: Maintenance, Refactoring
