Repository Freshly/flow, pull requests merged in 2019-04, with the labels that each got.

#28 Release - 0.9.2
  Gemfile.lock
  lib/flow/version.rb
Labels: Release

#26 Documentation
  README.md
  docs/images/error.png
  docs/images/flow.png
  docs/images/revert.png
  docs/images/transaction.png
  lib/flow/concerns/transaction_wrapper.rb
  lib/flow/flow/operations.rb
  lib/flow/flow/status.rb
  lib/flow/flow/transactions.rb
  lib/flow/flow_base.rb
  lib/flow/operation/core.rb
  lib/flow/operation/error_handler.rb
  lib/flow/operation/execute.rb
  lib/flow/operation/failures.rb
  lib/flow/operation/transactions.rb
  lib/flow/operation_base.rb
  lib/flow/state/attributes.rb
  lib/flow/state/core.rb
  lib/flow/state_base.rb
  spec/support/test_classes/bottles_on_the_wall_flow.rb
Labels: Feature

#31 Add #define_attribute custom matchers
  README.md
  lib/flow/custom_matchers.rb
  lib/flow/custom_matchers/define_attribute.rb
Labels: Feature

#32 Add double run protection to operation
  lib/flow/operation/errors/already_executed.rb
  lib/flow/operation/errors/already_rewound.rb
  lib/flow/operation/execute.rb
  lib/flow/operation/rewind.rb
  lib/flow/operation/status.rb
  lib/flow/operation_base.rb
  spec/operation/error_handler_spec.rb
  spec/operation/errors/already_executed_spec.rb
  spec/operation/errors/already_rewound_spec.rb
  spec/operation/execute_spec.rb
  spec/operation/rewind_spec.rb
  spec/operation/status_spec.rb
  spec/operation/transactions_spec.rb
  spec/spec_helper.rb
  spec/support/shared_examples/operation_double_runs_are_prevented.rb
Labels: Correction

#33 Documentation Update
  README.md
  lib/flow/state/attributes.rb
  lib/generators/flow/state/templates/state.rb.erb
  lib/generators/rspec/flow/templates/flow_spec.rb.erb
  lib/generators/rspec/operation/templates/operation_spec.rb.erb
  lib/generators/rspec/state/templates/state_spec.rb.erb
  spec/state/attributes_spec.rb
Labels: Feature

#41 Upgrade Spicerack
  Gemfile.lock
  flow.gemspec
  spec/spec_helper.rb
  spec/support/shared_context/with_callbacks.rb
  spec/support/shared_context/with_example_class_having_callback.rb
  spec/support/shared_examples/a_class_with_callback.rb
  spec/support/shared_examples/an_example_class_with_callbacks.rb
  spec/support/shared_examples/an_inherited_property.rb
Labels: Maintenance

#42 Spec Cleanup
  README.md
  lib/flow/custom_matchers/define_argument.rb
  lib/flow/custom_matchers/define_attribute.rb
  lib/flow/custom_matchers/define_option.rb
  lib/flow/custom_matchers/use_operations.rb
  spec/integration/bottles_on_the_wall_flow_spec.rb
  spec/integration/bottles_on_the_wall_state_spec.rb
  spec/integration/flow_integration_spec.rb
  spec/spec_helper.rb
  spec/support/test_classes/bottles_on_the_wall_state.rb
Labels: Feature, Refactoring

#43 wrap_in_transaction Custom Matcher
  .codeclimate.yml
  .rubocop.yml
  Gemfile.lock
  README.md
  flow.gemspec
  lib/flow/concerns/transaction_wrapper.rb
  lib/flow/custom_matchers.rb
  lib/flow/custom_matchers/define_option.rb
  lib/flow/custom_matchers/use_operations.rb
  lib/flow/custom_matchers/wrap_in_transaction.rb
  spec/integration/bottles_on_the_wall_flow_spec.rb
  spec/integration/count_out_current_bottles_spec.rb
  spec/integration/pass_bottles_around_spec.rb
  spec/integration/take_bottles_down_spec.rb
  spec/support/shared_examples/method_is_wrapped_in_a_transaction.rb
Labels: Feature

#47 define_failure custom matcher
  lib/flow/custom_matchers.rb
  lib/flow/custom_matchers/define_failure.rb
  lib/flow/custom_matchers/wrap_in_transaction.rb
  lib/generators/rspec/operation/templates/operation_spec.rb.erb
  spec/integration/pass_bottles_around_spec.rb
  spec/integration/take_bottles_down_spec.rb
Labels: Feature

#48 handle_error Matcher
  README.md
  lib/flow/custom_matchers.rb
  lib/flow/custom_matchers/define_failure.rb
  lib/flow/custom_matchers/handle_error.rb
  spec/integration/pass_bottles_around_spec.rb
  spec/integration/take_bottles_down_spec.rb
Labels: Feature

#49 Abstract Defaults
  lib/flow/custom_matchers/define_option.rb
  lib/flow/state/defaults.rb
  lib/flow/state/options.rb
  lib/flow/state_base.rb
  spec/flow/state/defaults/value_spec.rb
  spec/flow/state/defaults_spec.rb
  spec/flow/state/options/option_spec.rb
  spec/flow/state/options_spec.rb
  spec/flow/state_base_spec.rb
  spec/spec_helper.rb
  spec/support/shared_examples/a_class_with_attributes_having_default_values.rb
Labels: Precursor, Refactoring

#52 Move Default Triggering
  lib/flow/state/defaults.rb
  lib/flow/state/options.rb
  spec/flow/state/defaults/value_spec.rb
  spec/flow/state/defaults_spec.rb
Labels: Refactoring

#54 State Status
  lib/flow/state/status.rb
  lib/flow/state_base.rb
  spec/flow/state/status_spec.rb
  spec/flow/state_base_spec.rb
Labels: Precursor

#53 State Output
  lib/flow/state/errors/not_validated.rb
  lib/flow/state/options.rb
  lib/flow/state/output.rb
  lib/flow/state/string.rb
  lib/flow/state_base.rb
  spec/flow/state/errors/not_validated_spec.rb
  spec/flow/state/options_spec.rb
  spec/flow/state/output_spec.rb
  spec/flow/state/string_spec.rb
  spec/flow/state_base_spec.rb
  spec/spec_helper.rb
  spec/support/shared_examples/a_class_which_defines_into_a_class_collection.rb
Labels: Feature

#57 define_output Matcher & Integration Test
  lib/flow/custom_matchers.rb
  lib/flow/custom_matchers/define_option.rb
  lib/flow/custom_matchers/define_output.rb
  lib/flow/flow/core.rb
  lib/flow/flow/trigger.rb
  lib/flow/state/output.rb
  spec/flow/core_spec.rb
  spec/flow/state/output_spec.rb
  spec/integration/bottles_on_the_wall_state_spec.rb
  spec/integration/flow_integration_spec.rb
  spec/support/test_classes/bottles_on_the_wall_state.rb
  spec/support/test_classes/count_out_current_bottles.rb
  spec/support/test_classes/pass_bottles_around.rb
  spec/support/test_classes/take_bottles_down.rb
Labels: Feature

#58 Documentation Updates
  README.md
  lib/flow/state/output.rb
Labels: Maintenance

#68 Allow nil on arguments
  lib/flow/state/arguments.rb
  lib/flow/state/core.rb
  spec/flow/state/arguments_spec.rb
  spec/flow/state/core_spec.rb
  spec/support/shared_context/with_an_example_state.rb
Labels: Feature

#70 namespace objects in generated files
  lib/generators/rspec/application_flow/templates/application_flow_spec.rb
  lib/generators/rspec/application_operation/templates/application_operation_spec.rb
  lib/generators/rspec/application_state/templates/application_state_spec.rb
Labels: Correction

#78 add gemlock with updated bundler
  Gemfile.lock
Labels: Correction

#67 Proactive Failure Guard Clauses
  README.md
  lib/flow/operation/failures.rb
  spec/flow/operation/failures_spec.rb
  spec/integration/flow_integration_spec.rb
  spec/support/test_classes/pass_bottles_around.rb
  spec/support/test_classes/take_bottles_down.rb
Labels: Feature
