Repository Freshly/flow, pull requests merged in 2019-06, with the labels that each got.

#109 make spicerack reqs less pessimistic
  Gemfile.lock
  flow.gemspec
Labels: Discussion

#112 Allow triggering a Flow with a provided state instance
  README.md
  flow.gemspec
  lib/flow/flow/core.rb
  spec/flow/core_spec.rb
Labels: Feature

#113 Release 0.10.1
  CHANGELOG.md
  Gemfile.lock
  lib/flow/version.rb
Labels: Release

#114 Release 0.10.1
  CHANGELOG.md
  Gemfile.lock
  README.md
  flow.gemspec
  lib/flow.rb
  lib/flow/flow/core.rb
  lib/flow/spec_helper.rb
  lib/flow/spec_helper/custom_matchers.rb
  lib/flow/spec_helper/custom_matchers/define_failure.rb
  lib/flow/spec_helper/custom_matchers/define_output.rb
  lib/flow/spec_helper/custom_matchers/handle_error.rb
  lib/flow/spec_helper/custom_matchers/have_on_state.rb
  lib/flow/spec_helper/custom_matchers/use_operations.rb
  lib/flow/spec_helper/custom_matchers/wrap_in_transaction.rb
  lib/flow/spec_helper/rspec_configuration.rb
  lib/flow/spec_helper/shared_contexts.rb
  lib/flow/spec_helper/shared_contexts/with_failing_operation.rb
  lib/flow/spec_helper/shoulda_matcher_helper.rb
  lib/flow/state_base.rb
  lib/flow/version.rb
  spec/flow/core_spec.rb
  spec/flow/spec_helpers/with_failing_operation_spec.rb
  spec/flow/state/output_spec.rb
  spec/flow/state_base_spec.rb
  spec/integration/bottles_on_the_wall_flow_spec.rb
  spec/integration/flow_integration_spec.rb
  spec/support/shared_context/with_an_example_state.rb
  spec/support/test_classes/bottles_on_the_wall_flow.rb
Labels: Release
