Repository Freshly/flow, pull requests merged in 2020-01, with the labels that each got.

#162 operation failures aren't necessarily errors
  lib/flow/flow/flux.rb
  spec/flow/flux_spec.rb
Labels: Correction

#128 Operation StateProxy
  CHANGELOG.md
  DEPRECATION_NOTICE.md
  README.md
  lib/flow.rb
  lib/flow/operation/core.rb
  lib/flow/state_proxy.rb
  spec/flow/operation/accessors_spec.rb
  spec/flow/operation/core_spec.rb
  spec/flow/state_proxy_spec.rb
  spec/support/shared_context/with_an_example_operation.rb
  spec/support/shared_context/with_an_example_state.rb
  spec/support/test_classes/count_out_current_bottles.rb
  spec/support/test_classes/pass_bottles_around.rb
  spec/support/test_classes/take_bottles_down.rb
Labels: Feature

#131 Console Examples
  bin/console
Labels: Correction

#135 State Writer Integration Test
  CHANGELOG.md
  Gemfile.lock
  flow.gemspec
  spec/integration/bottle_spec.rb
  spec/integration/create_auth_token_spec.rb
  spec/integration/flow_integration_spec.rb
  spec/integration/sign_in_flow_spec.rb
  spec/integration/sign_in_state_spec.rb
  spec/integration/user_spec.rb
  spec/spec_helper.rb
  spec/support/shared_context/with_a_bottles_active_record.rb
  spec/support/shared_context/with_a_users_active_record.rb
  spec/support/shared_examples/credentials_are_validated.rb
  spec/support/test_classes/concerns/valid_credentials.rb
  spec/support/test_classes/create_auth_token.rb
  spec/support/test_classes/sign_in_flow.rb
  spec/support/test_classes/sign_in_state.rb
  spec/support/test_classes/user.rb
Labels: Feature

#136 State Accessor Matchers & README
  CHANGELOG.md
  README.md
  lib/flow/rspec/configuration.rb
  lib/flow/rspec/custom_matchers.rb
  lib/flow/rspec/custom_matchers/access_state.rb
  lib/flow/rspec/custom_matchers/define_failure.rb
  lib/flow/rspec/custom_matchers/define_output.rb
  lib/flow/rspec/custom_matchers/handle_error.rb
  lib/flow/rspec/custom_matchers/have_on_state.rb
  lib/flow/rspec/custom_matchers/read_state.rb
  lib/flow/rspec/custom_matchers/use_operations.rb
  lib/flow/rspec/custom_matchers/wrap_in_transaction.rb
  lib/flow/rspec/custom_matchers/write_state.rb
  lib/flow/rspec/shared_contexts.rb
  lib/flow/rspec/shared_contexts/with_failing_operation.rb
  lib/flow/rspec/shoulda_matcher_helper.rb
  lib/flow/spec_helper.rb
  lib/generators/flow/operation/templates/operation.rb.erb
  lib/generators/rspec/operation/templates/operation_spec.rb.erb
  spec/integration/count_out_current_bottles_spec.rb
  spec/integration/create_auth_token_spec.rb
  spec/integration/pass_bottles_around_spec.rb
  spec/integration/take_bottles_down_spec.rb
  spec/spec_helper.rb
  spec/support/test_classes/count_out_current_bottles.rb
  spec/support/test_classes/pass_bottles_around.rb
  spec/support/test_classes/take_bottles_down.rb
Labels: Feature

#149 Remodularize
  CHANGELOG.md
  lib/flow/flow/callbacks.rb
  lib/flow/flow/core.rb
  lib/flow/flow/errors/state_invalid.rb
  lib/flow/flow/flux.rb
  lib/flow/flow/operations.rb
  lib/flow/flow/status.rb
  lib/flow/flow/transactions.rb
  lib/flow/flow/trigger.rb
  lib/flow/flow_base.rb
  lib/flow/operation/core.rb
  lib/flow/operation_base.rb
  lib/flow/state/output.rb
  lib/flow/state_base.rb
  spec/flow/errors/state_invalid_spec.rb
  spec/flow/flow/callbacks_spec.rb
  spec/flow/flow/core_spec.rb
  spec/flow/flow/flux/failure_spec.rb
  spec/flow/flow/flux_spec.rb
  spec/flow/flow/operations_spec.rb
  spec/flow/flow/status_spec.rb
  spec/flow/flow/transactions_spec.rb
  spec/flow/flow/trigger_spec.rb
  spec/flow/flow_base_spec.rb
  spec/integration/flow_integration_spec.rb
  spec/spec_helper.rb
  spec/support/shared_context/with_example_flow_having_state.rb
Labels: Refactoring

#145 Use Root Object
  CHANGELOG.md
  lib/flow/flow_base.rb
  lib/flow/operation_base.rb
  spec/flow/flow_base_spec.rb
  spec/flow/operation_base_spec.rb
Labels: Refactoring

#132 Cleanup Generators
  lib/generators/rspec/application_operation/templates/application_operation_spec.rb
Labels: Correction

#150 Consolidate Errors
  CHANGELOG.md
  lib/flow.rb
  lib/flow/flow/errors/state_invalid.rb
  lib/flow/flow/trigger.rb
  lib/flow/flow_base.rb
  lib/flow/operation/errors/already_executed.rb
  lib/flow/operation/errors/already_rewound.rb
  lib/flow/operation/execute.rb
  lib/flow/operation_base.rb
  lib/flow/state/errors/not_validated.rb
  lib/flow/state/output.rb
  lib/flow/state_base.rb
  spec/flow/errors/state_invalid_spec.rb
  spec/flow/flow/trigger_spec.rb
  spec/flow/operation/errors/already_executed_spec.rb
  spec/flow/operation/errors/already_rewound_spec.rb
  spec/flow/operation/execute_spec.rb
  spec/flow/state/errors/not_validated_spec.rb
  spec/flow/state/output_spec.rb
  spec/flow_spec.rb
  spec/integration/flow_integration_spec.rb
Labels: Refactoring

#151 Full Class Example Objects
  spec/flow/flow/core_spec.rb
  spec/flow/operation/accessors_spec.rb
  spec/flow/operation/core_spec.rb
  spec/flow/operation/error_handler_spec.rb
  spec/flow/operation/execute_spec.rb
  spec/flow/operation/failures_spec.rb
  spec/flow/operation/status_spec.rb
  spec/flow/operation/transactions_spec.rb
  spec/flow/state/output_spec.rb
  spec/flow/state/status_spec.rb
  spec/support/shared_context/with_an_example_operation.rb
  spec/support/shared_context/with_an_example_state.rb
  spec/support/shared_context/with_example_flow_having_state.rb
Labels: Refactoring

#164 Release 0.10.5
  Gemfile.lock
  lib/flow/version.rb
Labels: Release

#152 Use Conjunction Junction
  Gemfile.lock
  flow.gemspec
  lib/flow.rb
  lib/flow/flow/core.rb
  lib/flow/flow_base.rb
  lib/flow/state_base.rb
  spec/flow/flow/core_spec.rb
  spec/flow/flow_base_spec.rb
  spec/flow/state_base_spec.rb
  spec/spec_helper.rb
Labels: Feature

#166 Release 0.10.6
  CHANGELOG.md
  Gemfile.lock
  lib/flow/version.rb
Labels: Feature

#167 Release 0.10.6
  CHANGELOG.md
  Gemfile.lock
  flow.gemspec
  lib/flow.rb
  lib/flow/flow/core.rb
  lib/flow/flow_base.rb
  lib/flow/state_base.rb
  lib/flow/version.rb
  spec/flow/flow/core_spec.rb
  spec/flow/flow_base_spec.rb
  spec/flow/state_base_spec.rb
  spec/spec_helper.rb
Labels: Release

#153 Use Malfunction
  Gemfile.lock
  flow.gemspec
  lib/flow.rb
  lib/flow/malfunction/base.rb
  spec/flow/malfunction/base_spec.rb
  spec/integration/user_spec.rb
Labels: Precursor

#169 Gem Updates
  Gemfile.lock
  flow.gemspec
Labels: Maintenance
